import { scale } from "react-native-size-matters";

export const APP = {
  SHOW_LOG: true,
  
  MAX_FILE_SIZE: 10, // 10 MB
  ACTIVE_OPACITY: 0.65,

  SQUARE_IMAGE_SIZE: 500,
  LONG_DIGIT_NOTIFICATION_COUNT: "99+",

  // Images or Icons Size
  HEADER_HEIGHT: scale(44),
  BORDER_WIDTH: scale(1),
  
  BACK_ICON_SIZE: 16,

  TEXT_FIELD_BORDER_RADIUS: scale(5),
  TEXT_FIELD_HEIGHT: scale(35),
  TEXT_FIELD_SEARCH_HEIGHT: 44,

  //Fonts Size
  MAIN_HEADER_RIGHT_FONT_SIZE: 13,
  MAIN_HEADER_LEFT_FONT_SIZE: 15,
  FONT_SIZE_10: 10,
  FONT_SIZE_11: 11,
  FONT_SIZE_12: 12,
  FONT_SIZE_13: 13,
  FONT_SIZE_14: 14,
  DEFAULT_TEXT_INPUT_LABEL_SIZE: 11,
  APP_NOTIFICATION_COUNT_FONT_SIZE: 8,
  EVENT_STATUS_FONT_SIZE: 8,
};
